force-app/main/default/objects/ID_Card_Request__c/ID_Card_Request__c.object-meta.xml
<CustomObject>
    <label>ID_Card_Request</label>
    <nameField>
        <label>ID_Card_Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ID_Card_Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ID_Card_Request__c/fields/Photo_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Photo_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Photo Uploaded</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ID_Card_Request__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ID_Card_Request__c/fields/Request_No__c.field-meta.xml
<CustomField>
    <fullName>Request_No__c</fullName>
    <label>Request No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/ID_Card_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Issued</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ID_Card_Request__c/fields/Student1__c.field-meta.xml
<CustomField>
    <fullName>Student1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student1</label>
    <referenceTo>Student1__c</referenceTo>
    <relationshipLabel>ID_Card_Requests</relationshipLabel>
    <relationshipName>ID_Card_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student1__c/Student1__c.object-meta.xml
<CustomObject>
    <label>Student1</label>
    <nameField>
        <label>Student1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/IDCardController.cls
public with sharing class IDCardController {

    @AuraEnabled(cacheable=true)
    public static List<ID_Card_Request__c> getAllIDCards(){

        return[
            SELECT Id,
                   Name,
                   Request_No__c,
                   Student1__c,
                   Reason__c,
                   Photo_Uploaded__c,
                   Request_Date__c,
                   Issue_Date__c,
                   Status__c
            FROM ID_Card_Request__c
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static ID_Card_Request__c getIDCard(Id requestId){

        return[
            SELECT Id,
                   Name,
                   Request_No__c,
                   Student1__c,
                   Reason__c,
                   Photo_Uploaded__c,
                   Request_Date__c,
                   Issue_Date__c,
                   Status__c
            FROM ID_Card_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static String issueIDCard(Id requestId){

        ID_Card_Request__c card=[
            SELECT Id,
                   Status__c,
                   Issue_Date__c
            FROM ID_Card_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];

        card.Status__c='Issued';
        card.Issue_Date__c=Date.today();

        update card;

        return 'ID Card Issued Successfully';
    }

    @AuraEnabled
    public static String updateStatus(Id requestId,String status){

        ID_Card_Request__c card=[
            SELECT Id,Status__c
            FROM ID_Card_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];

        card.Status__c=status;

        update card;

        return 'Status Updated Successfully';
    }

}