force-app/main/default/objects/Complaint1__c/Complaint1__c.object-meta.xml
<CustomObject>
    <label>Complaint1</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Complaint No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Complaints1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Complaint1__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Complaints1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint1__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Academic</fullName>
            </value>
            <value>
                <fullName>Hostel</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Finance</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Complaint1__c/fields/Student1__c.field-meta.xml
<CustomField>
    <fullName>Student1__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Student1</label>
    <referenceTo>Student1__c</referenceTo>
    <relationshipLabel>Complaints1</relationshipLabel>
    <relationshipName>Complaints</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Complaint1__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>Subject</label>
    <length>13</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student1__c/Student1__c.object-meta.xml
<CustomObject>
    <label>Student1</label>
    <nameField>
        <label>Student1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ComplaintController.cls
public with sharing class ComplaintController {

    @AuraEnabled(cacheable=true)
    public static List<Complaint1__c> getAllComplaints(){

        return[
            SELECT Id,
                   Name,
                   Student1__c,
                   Category__c,
                   Subject__c,
                   Description__c,
                   Priority__c,
                   Status__c,
                   Assigned_To__c
            FROM Complaint1__c
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Complaint1__c getComplaint(Id complaintId){

        return[
            SELECT Id,
                   Name,
                   Student1__c,
                   Category__c,
                   Subject__c,
                   Description__c,
                   Priority__c,
                   Status__c,
                   Assigned_To__c
            FROM Complaint1__c
            WHERE Id=:complaintId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static String closeComplaint(Id complaintId){

        Complaint1__c comp=[
            SELECT Id,Status__c
            FROM Complaint1__c
            WHERE Id=:complaintId
            LIMIT 1
        ];

        comp.Status__c='Closed';

        update comp;

        return 'Complaint Closed Successfully';
    }

    @AuraEnabled
    public static String updateComplaintStatus(Id complaintId,String status){

        Complaint1__c comp=[
            SELECT Id,Status__c
            FROM Complaint1__c
            WHERE Id=:complaintId
            LIMIT 1
        ];

        comp.Status__c=status;

        update comp;

        return 'Complaint Updated Successfully';
    }

}