force-app/main/default/objects/Certificate_request__c/Certificate_request__c.object-meta.xml
<CustomObject>
    <label>Certificate request</label>
    <nameField>
        <label>Certificate request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Certificate requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certificate_request__c/fields/Certificate_Type__c.field-meta.xml
<CustomField>
    <fullName>Certificate_Type__c</fullName>
    <label>Certificate Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bonafide</fullName>
            </value>
            <value>
                <fullName>TC</fullName>
            </value>
            <value>
                <fullName>Conduct</fullName>
            </value>
            <value>
                <fullName>Course Completion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificate_request__c/fields/Request_No__c.field-meta.xml
<CustomField>
    <fullName>Request_No__c</fullName>
    <displayFormat>PS-{000}</displayFormat>
    <label>Request No</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Certificate_request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Certificate_request__c/fields/Student1__c.field-meta.xml
<CustomField>
    <fullName>Student1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student1</label>
    <referenceTo>Student1__c</referenceTo>
    <relationshipLabel>Certificate requests</relationshipLabel>
    <relationshipName>Certificate_requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certificate_request__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Certificate_requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student1__c/Student1__c.object-meta.xml
<CustomObject>
    <label>Student1</label>
    <nameField>
        <label>Student1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CertificateController.cls
public with sharing class CertificateController {

    @AuraEnabled(cacheable=true)
    public static List<Certificate_Request__c> getAllCertificateRequests(){

        return[
            SELECT Id,
                   Name,
                   Request_No__c,
                   Student1__c,
                   Certificate_Type__c,
                   Reason__c,
                   Applied_Date__c,
                   Required_Date__c,
                   Status__c,
                   User__c
            FROM Certificate_Request__c
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled(cacheable=true)
    public static Certificate_Request__c getCertificateRequest(Id requestId){

        return[
            SELECT Id,
                   Name,
                   Request_No__c,
                   Student1__c,
                   Certificate_Type__c,
                   Reason__c,
                   Applied_Date__c,
                   Required_Date__c,
                   Status__c,
                   User__c
            FROM Certificate_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];
    }

    @AuraEnabled
    public static String approveCertificate(Id requestId){

        Certificate_Request__c req=[
            SELECT Id,Status__c
            FROM Certificate_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];

        req.Status__c='Approved';

        update req;

        return 'Certificate Approved Successfully';
    }

    @AuraEnabled
    public static String rejectCertificate(Id requestId){

        Certificate_Request__c req=[
            SELECT Id,Status__c
            FROM Certificate_Request__c
            WHERE Id=:requestId
            LIMIT 1
        ];

        req.Status__c='Rejected';

        update req;

        return 'Certificate Rejected Successfully';
    }

}