force-app/main/default/objects/Hostel__c/Hostel__c.object-meta.xml
<CustomObject>
    <label>Hostel</label>
    <nameField>
        <label>Hostel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hostels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/Room__c.object-meta.xml
<CustomObject>
    <label>Room</label>
    <nameField>
        <label>Room Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Room__c/fields/Current_Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Current_Occupancy__c</fullName>
    <label>Current Occupancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Room__c/fields/Hostel__c.field-meta.xml
<CustomField>
    <fullName>Hostel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hostel</label>
    <referenceTo>Hostel__c</referenceTo>
    <relationshipLabel>Rooms</relationshipLabel>
    <relationshipName>Rooms</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RoomAvailabilityService.cls
public with sharing class RoomAvailabilityService {

    public static Boolean isRoomAvailable(Id roomId){

        Room__c room = [

            SELECT Id,
                   Capacity__c,
                   Current_Occupancy__c,
                   Availability__c
            FROM Room__c
            WHERE Id=:roomId
            LIMIT 1

        ];

        if(!room.Availability__c){
            return false;
        }

        return room.Current_Occupancy__c < room.Capacity__c;

    }

    public static Integer getAvailableRooms(Id hostelId){

        return [

            SELECT COUNT()

            FROM Room__c

            WHERE Hostel__c=:hostelId

            AND Availability__c = true

        ];

    }

    public static Integer getOccupiedRooms(Id hostelId){

        return [

            SELECT COUNT()

            FROM Room__c

            WHERE Hostel__c=:hostelId

            AND Availability__c = false

        ];

    }

    public static void updateRoomStatus(Set<Id> roomIds){

        List<Room__c> rooms=[

            SELECT Id,
                   Capacity__c,
                   Current_Occupancy__c

            FROM Room__c

            WHERE Id IN :roomIds

        ];

        for(Room__c r:rooms){

            if(r.Current_Occupancy__c>=r.Capacity__c){

                r.Availability__c = false;

            }
            else{

                r.Availability__c = true;

            }

        }

        update rooms;

    }

}