force-app/main/default/objects/Scholarship__c/Scholarship__c.object-meta.xml
<CustomObject>
    <label>Scholarship</label>
    <nameField>
        <label>Scholarship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Scholarships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Scholarship__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Scholarship__c/fields/Provider__c.field-meta.xml
<CustomField>
    <fullName>Provider__c</fullName>
    <label>Provider</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Scholarship__c/fields/Student1__c.field-meta.xml
<CustomField>
    <fullName>Student1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student1</label>
    <referenceTo>Student1__c</referenceTo>
    <relationshipLabel>Scholarships</relationshipLabel>
    <relationshipName>Scholarships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student1__c/Student1__c.object-meta.xml
<CustomObject>
    <label>Student1</label>
    <nameField>
        <label>Student1 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students1</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ScholarshipController.cls
public with sharing class ScholarshipController {

    @AuraEnabled(cacheable=true)
    public static List<Scholarship__c> getAllScholarships(){

        return[
            SELECT Id,
                   Name,
                   Student1__c,
                   Provider__c,
                   Percentage__c,
                   Amount__c,
                   Approval_Status__c,
                   Applied_Date__c,
                   Approved_Date__c
            FROM Scholarship__c
            ORDER BY CreatedDate DESC
        ];
    }

    @AuraEnabled
    public static String approveScholarship(Id scholarshipId){

        Scholarship__c s=[SELECT Id,Approval_Status__c,Approved_Date__c
                          FROM Scholarship__c
                          WHERE Id=:scholarshipId
                          LIMIT 1];

        s.Approval_Status__c='Approved';
        s.Approved_Date__c=Date.today();

        update s;

        return 'Scholarship Approved';
    }

}