force-app/main/default/objects/Staff__c/Staff__c.object-meta.xml
<CustomObject>
    <description>Staff members of the college hostel management system.</description>
    <label>Staff</label>
    <nameField>
        <displayFormat>STF-{0000}</displayFormat>
        <label>Staff ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staff</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staff__c/fields/experience__c.field-meta.xml
<CustomField>
    <fullName>experience__c</fullName>
    <label>experience</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/ID__c.field-meta.xml
<CustomField>
    <fullName>ID__c</fullName>
    <displayFormat>ID-{000}</displayFormat>
    <label>ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Leave_Count__c.field-meta.xml
<CustomField>
    <fullName>Leave_Count__c</fullName>
    <formula>Leave_End_Date__c  -  Leave_Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Leave Count</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Licensenum__c.field-meta.xml
<CustomField>
    <fullName>Licensenum__c</fullName>
    <label>Licensenum</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Staff__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/StaffController.cls
public with sharing class StaffController {
    @AuraEnabled(cacheable=true)
    public static List<Staff__c> getStaffRecords(Integer limitSize) {
        if (limitSize == null || limitSize <= 0) {
            limitSize = 10;
        }
        return [
            SELECT Id, Name__c, ID__c, Licensenum__c, experience__c, Status__c, 
                 Contact_Number__c, Email__c, Leave_Start_Date__c, Leave_End_Date__c,Leave_Count__c
            FROM Staff__c
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
            LIMIT :limitSize
        ];
    }
}